<a href="https://colab.research.google.com/github/EvelynJazminVelazquez/INTELIGENCIA-ARTIFICIAL-2024-2/blob/master/martes%205%20noviembre%202024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [2]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [3]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [4]:
matrixB=np.random.randint(0,10, size=(4,3))
print(matrixB)
print(matrixB.shape)

[[8 0 7]
 [8 7 4]
 [1 1 1]
 [0 2 4]]
(4, 3)


In [7]:
print(matrixB)
col_indices=np.array([0,1,2])
row_indices=np.arange(1,2)

for row,col in zip(row_indices,col_indices):
    #print(row,"-",col)
    print(matrixB[row,col])


[[8 0 7]
 [8 7 4]
 [1 1 1]
 [0 2 4]]
8


In [8]:
mask=matrixB>7
print(mask)

[[ True False False]
 [ True False False]
 [False False False]
 [False False False]]


In [9]:
print(matrixB[mask])

[8 8]


In [10]:
print(matrixB[matrixB>7])

[8 8]


In [15]:
matrixB[matrixB%2==0]+=100
print(matrixB)

[[108 100   7]
 [108   7 104]
 [  1   1   1]
 [100 102 104]]


In [17]:
print(matrixB)

[[108 100   7]
 [108   7 104]
 [  1   1   1]
 [100 102 104]]


In [18]:
matrixC = np.random.rand(2,2)

In [19]:
filter=(matrixB>3) & (matrixB<9)
matrixB[filter]+=100
print(matrixB)


[[108 100 107]
 [108 107 104]
 [  1   1   1]
 [100 102 104]]


In [21]:
matrixA1 = np.random.randint(0,10, size=(2,2))
matrixA2 = np.random.randint(0,10, size=(2,2))
print("matrixA1")
print(matrixA1)
print("matrixA2")
print(matrixA2)


matrixA1
[[4 9]
 [9 4]]
matrixA2
[[6 0]
 [8 4]]


In [22]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)

[[10  9]
 [17  8]]
[[-2  9]
 [ 1  0]]
[[24  0]
 [72 16]]
[[0.66666667        inf]
 [1.125      1.        ]]


<ipython-input-22-d9a4810fe26b>:4: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)


In [24]:
print(np.sqrt(matrixA1))

[[2. 3.]
 [3. 2.]]


In [26]:
matrixA1 = np.random.randint(0,10, size=(2,5))
print(matrixA1)

[[5 3 9 5 8]
 [8 9 7 5 7]]


In [27]:
print(np.mean(matrixA1))

6.6


In [28]:
print(matrixA1.mean(axis=1))

[6.  7.2]


In [29]:
print(matrixA1.mean(axis=0))

[6.5 6.  8.  5.  7.5]


In [30]:
print(np.std(matrixA1))

1.9078784028338913


In [31]:
print(np.median(matrixA1))

7.0


In [36]:
import builtins
print = builtins.print

print(matrixA1.sum())

66


In [37]:
print(matrixA1.max())

9


In [38]:
start=np.zeros((4,2))
print(start)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [39]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [40]:
print(start)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [41]:
col_rows=np.array([[1,2,3,4]])


In [43]:
print(start)
tmp=col_rows.T
y2=start+tmp
print(y2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]]


In [50]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [51]:
print(np.dot(tmp1,tmp2))

[[ 7  7]
 [14 14]]


In [53]:
y1=np.random.randint(low=2,high=50, size=(2,2))
y2=np.random.randint(low=2,high=50, size=(2,2))
print(y1)
print(y2)

[[44 11]
 [32 35]]
[[23  9]
 [ 7 38]]


In [54]:
np.vstack((y1,y2))

array([[44, 11],
       [32, 35],
       [23,  9],
       [ 7, 38]])

In [55]:
np.hstack((y1,y2))

array([[44, 11, 23,  9],
       [32, 35,  7, 38]])