<a href="https://colab.research.google.com/github/EvelynJazminVelazquez/INTELIGENCIA-ARTIFICIAL-2024-2/blob/main/Martes%2029/10/2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY LIBRARY

In [6]:
import numpy as np

In [7]:
 print(np.__version__)

1.26.4


In [8]:
myArray = np.array([1,2,3,4,5])
print(myArray)


[1 2 3 4 5]


In [9]:
print(type(myArray))

<class 'numpy.ndarray'>


In [12]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray)

(5,)
3
[ 1  2 29  4  5]


In [14]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
myArray3=np.zeros((5,5))
print(myArray3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
myArray4=np.full((3,6),10)
print(myArray4)
myArray5=np.eye(5)
print(myArray5)
myArray6=np.ones((5,5))
print(myArray6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
myArray7=np.random.random((5,5))
print(myArray7)

[[0.98010471 0.23944151 0.1829838  0.67848664 0.31127796]
 [0.90828898 0.68050605 0.77423303 0.53526451 0.18206945]
 [0.13842128 0.21412185 0.50791699 0.92295051 0.35429728]
 [0.60258759 0.82632448 0.04754695 0.01303635 0.96231262]
 [0.41191408 0.91894414 0.41655699 0.70753033 0.02845899]]


In [21]:
myArray8=np.random.randint(100,size=(5,5))
print(myArray8)

[[94 45  7 18 98]
 [65 47 53 31 96]
 [80 98 85 29 44]
 [28 55  5 93 56]
 [10 36  7 56 45]]


In [24]:
newMatrix=myArray8[3:, 3:]
print(newMatrix)

[[93 56]
 [56 45]]


In [26]:
myArray8[2,2]=10000
print(myArray8)

[[   94    45     7    18    98]
 [   65    47    53    31    96]
 [   80    98 10000    29    44]
 [   28    55     5    93    56]
 [   10    36     7    56    45]]


In [27]:
print(myArray8[2,:])

[   80    98 10000    29    44]


In [35]:
print(myArray8[:,2].shape)

(5,)


In [36]:
print(myArray8[1:4,1:4])


[[   47    53    31]
 [   98 10000    29]
 [   55     5    93]]
